apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-lhnk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-lhnk
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-lhnk
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-lhnk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-lhnk
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-ccmk-tenant/appstudio/dc-metro-map-lhnk@sha256:e09be2a2b207e0633ecb6d31127920bb7d9634262c4e58b842a06ad8c73c7875
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
