apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-opoj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-opoj
    app.kubernetes.io/part-of: appstudio
  name: devfile-sample-python-basic-opoj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-opoj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-opoj
    spec:
      containers:
      - image: quay.io/qijing/push-pyxis-ccmk-tenant/appstudio/devfile-sample-python-basic-opoj@sha256:fb0efbca7a3d9e27b6a2d34e53472e4e49d28c4ceab054faec01ed87ef02006f
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
